{% set name = "optree" %}
{% set version = "0.13.1" %}
{% set sha256 = "af67856aa8073d237fe67313d84f8aeafac32c1cef7239c628a2768d02679c43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [python_impl == 'pypy']
  script: |
    {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:   # [win]
    # Unset `CMAKE_GENERATOR` and let Visual Studio set to its default
    - CMAKE_GENERATOR=  # [win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.18  # to support `CMAKE_GENERATOR`
    - make                                # [not win]
  host:
    - pip
    - setuptools
    - python
    - pybind11 >=2.12
  run:
    - python
    - typing-extensions >=4.5

test:
  imports:
    - optree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metaopt/optree
  summary: Optimized PyTree Utilities
  dev_url: https://github.com/metaopt/optree
  doc_url: https://optree.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
