{% set name = "optree" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c7e2de5e5ba3a221dab3c4d245edc615373f582d36ac85cc3ec66c8cd190d76

build:
  skip: True            # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:           # [win]
    # Unset `CMAKE_GENERATOR` and let Visual Studio set to its default
    - CMAKE_GENERATOR=  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15  # to support `CMAKE_GENERATOR`
    - make          # [not win]
  host:
    - pip
    - python
    - pybind11 >=2.10.1
  run:
    - python
    - typing-extensions >=4.0.0

test:
  imports:
    - optree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metaopt/optree
  summary: Optimized PyTree Utilities
  dev_url: https://github.com/metaopt/optree
  doc_url: https://optree.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
