{% set name = "optree" %}
{% set version = "0.11.0" %}
{% set sha256 = "8e6a46e95c3ea8546055087d6fe52a1dcd56de5182365f1469106cc72cdf3307" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [python_impl == 'pypy']
  script: |
    {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:   # [win]
    # Unset `CMAKE_GENERATOR` and let Visual Studio set to its default
    - CMAKE_GENERATOR=  # [win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.15  # to support `CMAKE_GENERATOR`
    - make                                # [not win]
  host:
    - pip
    - python
    - pybind11 >=2.11.1
  run:
    - python
    - typing-extensions >=4.0.0

test:
  imports:
    - optree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metaopt/optree
  summary: Optimized PyTree Utilities
  dev_url: https://github.com/metaopt/optree
  doc_url: https://optree.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - XuehaiPan
